### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by ayrton** [ayrton/react-cluster#6]
This is currently planned for the `1.0` release:
- [x] examples and usage in the readme
- [ ] homepage with examples
- [ ] computed row heights
- [ ] different row heights
- [x] emit an event when scrolled to top and bottom for infinite scroll implementation

Obviously any other suggestions are appreciated. 🙌
